import React from 'react'

export default function Header() {
  return (
    <div>            <div style={{ gridTemplateColumns: '200px auto 200px', height: '64px', borderBottom: '0.8px solid rgb(245, 245, 245)', WebkitBoxAlign: 'center', alignItems: 'center', display: 'grid', color: 'rgb(0, 0, 0)', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', margin: '0px', padding: '0px', border: '0px', verticalAlign: 'baseline' }}>
    <div style={{ color: 'rgb(0, 0, 0)', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', margin: '0px', padding: '0px', border: '0px none rgb(0, 0, 0)', verticalAlign: 'baseline' }}><button style={{ display: 'flex', WebkitBoxPack: 'start', justifyContent: 'flex-start', WebkitBoxAlign: 'center', alignItems: 'center', paddingLeft: '20px', textDecoration: 'none solid rgb(0, 0, 0)', color: 'rgb(0, 0, 0)', outline: 'rgb(0, 0, 0) none 0px', border: '0px none rgb(0, 0, 0)', background: 'rgba(0, 0, 0, 0) none repeat scroll 0px 50% / auto padding-box border-box', cursor: 'pointer', padding: '0px 0px 0px 20px', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box' }}><svg width="25px" height="25px" viewBox="0 0 25 25" version="1.1" xmlns="http://www.w3.org/2000/svg" style={{ width: '30px', height: '30px', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}>
        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}>
            <g style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}>
                <circle fill="var(--DatePicker-DatepickerArrowButton-background)" fill-rule="nonzero" cx="12.5" cy="12.5" r="12.5" style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}></circle>
                <g transform="translate(5.000000, 5.000000)" style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}>
                    <polygon points="0 0 15 0 15 15 0 15" style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}></polygon>
                    <polygon fill="var(--GlobalColorScheme-ChevronSvg-datepickerRightLeft)" fill-rule="nonzero" transform="translate(6.776500, 7.523500) rotate(180.000000) translate(-6.776500, -7.523500) " points="9.554 7.523 5.448 2.693 4.12 3.659 6.656 7.523 3.999 11.388 5.448 12.354 9.554 7.524" style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)' }}></polygon>
                </g>
            </g>
        </g>
    </svg></button></div>
    <div style={{ color: 'rgb(0, 0, 0)', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', margin: '0px', padding: '0px', border: '0px none rgb(0, 0, 0)', verticalAlign: 'baseline' }}><a href="/leagues/73/overview/europa-league-final-stage?season=2023-2024" style={{ display: 'flex', WebkitBoxPack: 'center', justifyContent: 'center', WebkitBoxAlign: 'center', alignItems: 'center', textDecoration: 'none solid rgb(0, 0, 0)', color: 'rgb(0, 0, 0)', outline: 'rgb(0, 0, 0) none 0px', border: '0px none rgb(0, 0, 0)', background: 'rgba(0, 0, 0, 0) none repeat scroll 0px 50% / auto padding-box border-box', cursor: 'pointer', padding: '0px', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', margin: '0px', verticalAlign: 'baseline' }}>
        <div style={{ width: '20px', height: '20px', marginRight: '15px', color: 'rgb(0, 0, 0)', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', margin: '0px 15px 0px 0px', padding: '0px', border: '0px none rgb(0, 0, 0)', verticalAlign: 'baseline' }}><img src="https://images.fotmob.com/image_resources/logo/leaguelogo/73.png" alt="" width="20" height="20" loading="lazy" style={{ fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', color: 'rgb(0, 0, 0)', margin: '0px', padding: '0px', border: '0px none rgb(0, 0, 0)', verticalAlign: 'baseline' }} /></div><span style={{ fontSize: '16px', lineHeight: '18px', color: 'rgb(0, 0, 0)', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', margin: '0px', padding: '0px', border: '0px none rgb(0, 0, 0)', verticalAlign: 'baseline' }}>Europa League Round of 32</span>
    </a></div>
    <div style={{ marginRight: '20px', color: 'rgb(0, 0, 0)', fontFamily: 'GTWalsheim-Rg, GTWalsheim-Md, Rubik, system, Arial, sans-serif', fontWeight: 400, fontFeatureSettings: '"ss01"', boxSizing: 'border-box', padding: '0px', border: '0px none rgb(0, 0, 0)', verticalAlign: 'baseline' }}>
       
    </div>
</div></div>
  )
}
