name: Continuous Integration

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: npm cache clean --force
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build --if-present

      - name: Run lint
        run: npm run lint

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          organization: "spawn005"
          projectKey: "SpawN005_BRAVO_Frontend"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bouzidijasser/bravofrontendtru:latest
          dockerfile: Dockerfile
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
